apiVersion: 1

datasources:
  - name: cache_stats
    isDefault: false
    url: http://host.docker.internal:8086
    type: influxdb
    user: influxadmin
    jsonData:
      dbName: cache_stats
      httpMode: GET
    secureJsonData:
      password: influxadminpassword
  - name: deliveryservice_stats
    isDefault: false
    url: http://host.docker.internal:8086
    type: influxdb
    user: influxadmin
    jsonData:
      dbName: deliveryservice_stats
      httpMode: GET
    secureJsonData:
      password: influxadminpassword
  - name: daily_stats
    isDefault: false
    url: http://host.docker.internal:8086
    type: influxdb
    user: influxadmin
    jsonData:
      dbName: daily_stats
      httpMode: GET
    secureJsonData:
      password: influxadminpassword
  - name: telegraf
    isDefault: false
    url: http://host.docker.internal:8086
    type: influxdb
    user: influxadmin
    jsonData:
      dbName: telegraf
      httpMode: GET
    secureJsonData:
      password: influxadminpassword